# Библиотека `pandas`: часть 1

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-pandas1.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

### Задание 1

Загрузить массив `NumPy` из файла `"arr_pandas.npy"` (как в задании к предыдущему модулю) и преобразовать его в датафрейм. Массив содержит данные по результатам соревнований Scottish Hill Races в 2000 году (полное описание на английском языке можно посмотреть на [странице](https://vincentarelbundock.github.io/Rdatasets/doc/DAAG/races2000.html) с документацией по исходному файлу с данными).

**Подсказка (преобразование в датафрейм):**

In [6]:
import numpy as np
arr=np.load("arr_pandas.npy",allow_pickle=True)
arr

array([['Aonach Mor Gondola', 2.0, 2000, 0.40361111111111103,
        0.518888888888889, 'uphill'],
       ['Broughton Brewery', 2.0, 650, 0.254444444444444,
        0.316666666666667, 'other'],
       ['El-Brim-Ick', 3.0, 750, 0.4858333333333329, 0.3891666666666671,
        'other'],
       ['The Devils Burdens', 21.0, 4100, 2.3997222222222203,
        3.09333333333333, 'relay'],
       ['Tiso Carnethy', 6.0, 2500, 0.782222222222222, 0.919166666666667,
        'hill'],
       ['Criffel', 7.0, 1800, 0.793333333333333, 1.00333333333333,
        'hill'],
       ['Chapelgill', 1.5, 1400, 0.31444444444444397, 0.3766666666666671,
        'hill'],
       ["Norman's Law", 5.0, 700, 0.4641666666666671, 0.609166666666667,
        'hill'],
       ['Craig Dunain', 6.0, 900, 0.546111111111111, 0.625833333333333,
        'hill'],
       ['Knockfarrel', 5.0, 1200, 0.623333333333333, 0.734166666666667,
        'hill'],
       ['Screel', 4.0, 1300, 0.45888888888888896, 0.543611111111111,
        'hill'],
       ['O.P.S. Clachnaben', 10.5, 3500, 1.2788888888888899,
        1.48777777777778, 'hill'],
       ['Hunters Bog', 4.5, 800, 0.40944444444444394,
        0.47777777777777797, 'other'],
       ['Aberfoyle Dash', 3.0, 1000, 0.3375, 0.38138888888888894,
        'uphill'],
       ['Manx Mountain', 30.5, 8000, 4.469722222222219, 5.52333333333333,
        'marathon'],
       ['Whangie Whizz', 3.5, 800, 0.39555555555555605,
        0.4641666666666671, 'hill'],
       ['Ben Rha', 7.5, 800, 0.738055555555555, 0.9972222222222221,
        'relay'],
       ["Stuc A'Chroin", 14.0, 5000, 1.98333333333333, 2.39888888888889,
        'hill'],
       ['29th Dumyat', 5.0, 1250, 0.552777777777778, 0.637777777777778,
        'hill'],
       ['Ben Lomond', 9.0, 3192, 1.03777777777778, 1.19916666666667,
        'hill'],
       ['Kinnoull', 4.0, 800, 0.387222222222222, 0.4525, 'hill'],
       ['Goatfell', 8.0, 2866, 1.22777777777778, 1.52638888888889,
        'hill'],
       ['Scottish Nuclear Kaim', 3.5, 1250, 0.43111111111111106, 0.54,
        'hill'],
       ['Ardoch Rig', 7.0, 600, 0.6788888888888891, 0.8372222222222221,
        'hill'],
       ['Culter Fell', 12.0, 4000, 1.7216666666666698, 1.98777777777778,
        'other'],
       ['Isle of Jura', 16.0, 7500, 3.11638888888889, 3.83944444444444,
        'other'],
       ['Scolty', 5.0, 800, 0.4958333333333329, 0.579166666666667,
        'hill'],
       ['Cornalees', 5.5, 800, 0.618333333333333, nan, 'hill'],
       ['12 Trig Trog', 46.0, 7500, 8.30694444444445, 13.547777777777801,
        'hill'],
       ['Kilpatricks', 6.0, 1400, 0.7397222222222221, 0.874166666666667,
        'hill'],
       ['Glas Tulaichean', 4.5, 2200, 0.563888888888889,
        0.670555555555556, 'other'],
       ['Traprain', 6.5, 650, 0.623888888888889, 0.7486111111111109,
        'hill'],
       ['Yetholm', 8.0, 2500, 1.19305555555556, 1.4511111111111101,
        'hill'],
       ['Ben Sheann', 2.5, 1400, 0.3816666666666671, 0.484722222222222,
        'hill'],
       ['Glen Rosa', 13.0, 5500, 2.22027777777778, 2.7047222222222205,
        'hill'],
       ['West Highland Way', 95.0, 9200, 15.4388888888889,
        18.8791666666667, 'other'],
       ['Tiso Seven Hills', 14.0, 2200, 1.54444444444444,
        1.8066666666666698, 'other'],
       ['Scottish Borders', 10.0, 2000, 1.19805555555556,
        1.44972222222222, 'hill'],
       ['Eildon Two', 4.5, 1500, 0.427222222222222, 0.507777777777778,
        'other'],
       ['Lairig Ghru', 28.0, 2100, 3.18638888888889, 3.7527777777777795,
        'other'],
       ['Cort-ma', 6.0, 1500, 0.7422222222222221, 0.8702777777777779,
        'hill'],
       ['White Tops', 6.0, 900, 0.5727777777777779, 0.695, 'hill'],
       ['Dollar', 6.0, 2000, 0.638333333333333, 0.7736111111111109,
        'hill'],
       ['Ben Tee', 9.0, 2950, 1.32777777777778, 1.78277777777778, 'hill'],
       ['Black Hill', 4.0, 600, 0.447777777777778, 0.532222222222222,
        'hill'],
       ['Glamaig', 4.5, 2400, 0.7447222222222221, 0.9361111111111109,
        'hill'],
       ['Urie Loch', 6.0, 1400, 0.7738888888888891, 1.015, 'hill'],
       ['Whiteash', 5.5, 728, 0.508888888888889, 0.768333333333333,
        'hill'],
       ['Meall Ant-Suidhe', 3.5, 1500, 0.465, 0.609722222222222, 'hill'],
       ['Half Ben Nevis', 5.0, 1200, 0.794166666666667, 1.03083333333333,
        'other'],
       ['Lochaber AC', 2.0, 900, 0.284722222222222, 0.360555555555556,
        'hill'],
       ['Lochaber Highland', 2.0, 900, 0.29416666666666696,
        0.47305555555555606, 'hill'],
       ['Mash Hill', 6.0, 2500, 0.794166666666667, 1.05194444444444,
        'hill'],
       ['Ben Rhinnes', 14.0, 4900, 1.97611111111111, 2.3558333333333303,
        'hill'],
       ['Beinn Lee', 7.0, 500, 0.716666666666667, 0.943333333333333,
        'hill'],
       ['Creag Dubh', 3.0, 1223, 0.46388888888888896, 0.601666666666667,
        'hill'],
       ['Glen Clova', 15.0, 5500, 2.5672222222222203, 2.9622222222222203,
        'hill'],
       ['Caerketton', 2.5, 800, 0.208611111111111, 0.24666666666666698,
        'hill'],
       ['Wideford', 5.5, 741, 0.563611111111111, 0.7241666666666671,
        'hill'],
       ["Tap O'North", 6.0, 1220, 0.6658333333333329, 0.8177777777777779,
        'hill'],
       ['Lomonds', 9.0, 2200, 1.05305555555556, 1.2938888888888898,
        'hill'],
       ['Oban', 2.25, 500, 0.23222222222222197, 0.298888888888889,
        'hill'],
       ['Ben Nevis', 10.0, 4400, 1.4261111111111102, 1.72361111111111,
        'hill'],
       ['Braemar', 4.0, 2000, 0.40777777777777796, nan, 'other'],
       ['Moffat Beef Tub', 2.0, 1500, 0.332222222222222,
        0.43694444444444397, 'hill'],
       ['Cairn William', 6.0, 1400, 0.704444444444444,
        0.8097222222222221, 'hill'],
       ['Corrieyairick', 16.0, 2250, 1.66472222222222, 1.96333333333333,
        'hill'],
       ['Morven', 5.0, 1700, 0.609166666666667, 0.7858333333333329,
        'hill'],
       ['Merrick', 8.0, 2710, 1.13333333333333, 1.39472222222222, 'hill'],
       ['Two Breweries', 18.0, 4900, 2.5658333333333303,
        3.0883333333333303, 'hill'],
       ['Manor Water', 10.0, 2300, 1.18444444444444, 1.4975, 'hill'],
       ['Pentland', 16.0, 6200, 2.3777777777777795, 2.785, 'hill'],
       ['Tinto', 4.5, 1500, 0.49944444444444397, 0.581111111111111,
        'hill'],
       ['Druim Fada', 6.5, 1000, 0.7511111111111108, 0.9722222222222221,
        'other'],
       ['Elrick', 3.6, 650, 0.35805555555555607, 0.4425, 'relay'],
       ['Gondola', 2.5, 2000, 0.387222222222222, 0.518888888888889,
        'uphill'],
       ['Greenmantle', 2.0, 650, 0.254444444444444, 0.316666666666667,
        'other']], dtype=object)

In [9]:
import pandas as pd
dat = pd.DataFrame(arr)
dat

                     0     1     2         3         4       5
0   Aonach Mor Gondola   2.0  2000  0.403611  0.518889  uphill
1    Broughton Brewery   2.0   650  0.254444  0.316667   other
2          El-Brim-Ick   3.0   750  0.485833  0.389167   other
3   The Devils Burdens  21.0  4100  2.399722  3.093333   relay
4        Tiso Carnethy   6.0  2500  0.782222  0.919167    hill
..                 ...   ...   ...       ...       ...     ...
72               Tinto   4.5  1500  0.499444  0.581111    hill
73          Druim Fada   6.5  1000  0.751111  0.972222   other
74              Elrick   3.6   650  0.358056    0.4425   relay
75             Gondola   2.5  2000  0.387222  0.518889  uphill
76         Greenmantle   2.0   650  0.254444  0.316667   other

[77 rows x 6 columns]

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [60]:
dat.shape  #77, 6#
dat
print ('77, 6')

77, 6

### Задание 3

Присвоить столбцам следующие названия (указаны с пояснениями): 

* `id`: id участника
* `dist`: расстояние в милях (по карте)
* `climb`: высота, достигнутая на маршруте (в сумме за весь маршрут, в футах)
* `time`: время (в часах)
* `timef`: время для женщин (в часах)
* `type`: тип гонки (*hill*, *marathon*, *relay*, *uphill* or *other*)

In [20]:
dat.columns=['id','dist','climb','time','timef','type']
dat

                    id  dist climb      time     timef    type
0   Aonach Mor Gondola   2.0  2000  0.403611  0.518889  uphill
1    Broughton Brewery   2.0   650  0.254444  0.316667   other
2          El-Brim-Ick   3.0   750  0.485833  0.389167   other
3   The Devils Burdens  21.0  4100  2.399722  3.093333   relay
4        Tiso Carnethy   6.0  2500  0.782222  0.919167    hill
..                 ...   ...   ...       ...       ...     ...
72               Tinto   4.5  1500  0.499444  0.581111    hill
73          Druim Fada   6.5  1000  0.751111  0.972222   other
74              Elrick   3.6   650  0.358056    0.4425   relay
75             Gondola   2.5  2000  0.387222  0.518889  uphill
76         Greenmantle   2.0   650  0.254444  0.316667   other

[77 rows x 6 columns]

### Задание 4

Вывести на экран значение высоты, достигнутой на маршруте участником *Norman's Law*.

In [41]:
#dat.iloc[7,0]-поиск самого участника,возникла проблема из-за апострофа в имени
dat.iloc[7,2]

700

### Задание 5
Вывести на экран значения показателей `dist`, `climb` , `time` для первых 10 участников.

In [46]:
dat.loc[0:9,['dist','climb','time']]

   dist climb      time
0   2.0  2000  0.403611
1   2.0   650  0.254444
2   3.0   750  0.485833
3  21.0  4100  2.399722
4   6.0  2500  0.782222
5   7.0  1800  0.793333
6   1.5  1400  0.314444
7   5.0   700  0.464167
8   6.0   900  0.546111
9   5.0  1200  0.623333

### Задание 6

Вывести на экран сводную информацию по датафрейму, которая включает типы всех столбцов. Сколько столбцов типа `float` в датафрейме? Привести ответ на вопрос в виде текста или комментария к коду.

In [64]:
dat #-Визуално тип float присутствует

                    id  dist climb      time     timef    type
0   Aonach Mor Gondola   2.0  2000  0.403611  0.518889  uphill
1    Broughton Brewery   2.0   650  0.254444  0.316667   other
2          El-Brim-Ick   3.0   750  0.485833  0.389167   other
3   The Devils Burdens  21.0  4100  2.399722  3.093333   relay
4        Tiso Carnethy   6.0  2500  0.782222  0.919167    hill
..                 ...   ...   ...       ...       ...     ...
72               Tinto   4.5  1500  0.499444  0.581111    hill
73          Druim Fada   6.5  1000  0.751111  0.972222   other
74              Elrick   3.6   650  0.358056    0.4425   relay
75             Gondola   2.5  2000  0.387222  0.518889  uphill
76         Greenmantle   2.0   650  0.254444  0.316667   other

[77 rows x 6 columns]

In [63]:
dat.info() #Но при запрове info тип float в DataFrame отсутствует
dat.select_dtypes('float') #Такой-же результат и при поиске в данном DataFrame данных типа float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      77 non-null     object
 1   dist    77 non-null     object
 2   climb   77 non-null     object
 3   time    77 non-null     object
 4   timef   75 non-null     object
 5   type    77 non-null     object
dtypes: object(6)
memory usage: 3.7+ KB

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]

[77 rows x 0 columns]

In [80]:
dat['dist']=dat['dist'].astype(float)
dat['time']=dat['time'].astype(float)
dat['timef']=dat['timef'].astype(float)
dat.info() #После тзменения типа данных в столбцах с плавающей точкой удалось обнаружить ячейки с требуемым типом
dat.select_dtypes('float')#Так же при поиске только ячеек с типом float мы можем визуально убедится в их наличии
#Всего нашлось 229 ячеек с типом float

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      77 non-null     object
 1   dist    77 non-null     float64
 2   climb   77 non-null     object
 3   time    77 non-null     float64
 4   timef   75 non-null     float64
 5   type    77 non-null     object
dtypes: float64(3), object(3)
memory usage: 3.7+ KB

    dist      time     timef
0    2.0  0.403611  0.518889
1    2.0  0.254444  0.316667
2    3.0  0.485833  0.389167
3   21.0  2.399722  3.093333
4    6.0  0.782222  0.919167
..   ...       ...       ...
72   4.5  0.499444  0.581111
73   6.5  0.751111  0.972222
74   3.6  0.358056  0.442500
75   2.5  0.387222  0.518889
76   2.0  0.254444  0.316667

[77 rows x 3 columns]

### Задание 7

Выбрать строки, которые соответствуют участникам эстафеты (*relay*).

In [82]:
dat[dat['type']=='relay']

                    id  dist climb      time     timef   type
3   The Devils Burdens  21.0  4100  2.399722  3.093333  relay
16             Ben Rha   7.5   800  0.738056  0.997222  relay
74              Elrick   3.6   650  0.358056  0.442500  relay

### Задание 8

Выбрать строки, которые соответствуют участникам гонки в холмах (*hill*), которые в сумме достигли высоты более 1000 футов. Посчитать, сколько таких участников.

In [86]:
dat[(dat['type']=='hill') & (dat['climb']>=1000)].shape[0]

39

### Задание 9

Выбрать строки, соответствующие участникам, которые либо достигли высоты более 4000 футов, либо потратили менее 0.5 часов.

In [87]:
dat[(dat['climb']>=4000) | (dat['time']<=0.5)]

                       id   dist climb       time      timef      type
0      Aonach Mor Gondola   2.00  2000   0.403611   0.518889    uphill
1       Broughton Brewery   2.00   650   0.254444   0.316667     other
2             El-Brim-Ick   3.00   750   0.485833   0.389167     other
3      The Devils Burdens  21.00  4100   2.399722   3.093333     relay
6              Chapelgill   1.50  1400   0.314444   0.376667      hill
7            Norman's Law   5.00   700   0.464167   0.609167      hill
10                 Screel   4.00  1300   0.458889   0.543611      hill
12            Hunters Bog   4.50   800   0.409444   0.477778     other
13         Aberfoyle Dash   3.00  1000   0.337500   0.381389    uphill
14          Manx Mountain  30.50  8000   4.469722   5.523333  marathon
15          Whangie Whizz   3.50   800   0.395556   0.464167      hill
17          Stuc A'Chroin  14.00  5000   1.983333   2.398889      hill
20               Kinnoull   4.00   800   0.387222   0.452500      hill
22  Scottish Nuclear Kaim   3.50  1250   0.431111   0.540000      hill
24            Culter Fell  12.00  4000   1.721667   1.987778     other
25           Isle of Jura  16.00  7500   3.116389   3.839444     other
26                 Scolty   5.00   800   0.495833   0.579167      hill
28           12 Trig Trog  46.00  7500   8.306944  13.547778      hill
33             Ben Sheann   2.50  1400   0.381667   0.484722      hill
34              Glen Rosa  13.00  5500   2.220278   2.704722      hill
35      West Highland Way  95.00  9200  15.438889  18.879167     other
38             Eildon Two   4.50  1500   0.427222   0.507778     other
44             Black Hill   4.00   600   0.447778   0.532222      hill
48       Meall Ant-Suidhe   3.50  1500   0.465000   0.609722      hill
50            Lochaber AC   2.00   900   0.284722   0.360556      hill
51      Lochaber Highland   2.00   900   0.294167   0.473056      hill
53            Ben Rhinnes  14.00  4900   1.976111   2.355833      hill
55             Creag Dubh   3.00  1223   0.463889   0.601667      hill
56             Glen Clova  15.00  5500   2.567222   2.962222      hill
57             Caerketton   2.50   800   0.208611   0.246667      hill
61                   Oban   2.25   500   0.232222   0.298889      hill
62              Ben Nevis  10.00  4400   1.426111   1.723611      hill
63                Braemar   4.00  2000   0.407778        NaN     other
64        Moffat Beef Tub   2.00  1500   0.332222   0.436944      hill
69          Two Breweries  18.00  4900   2.565833   3.088333      hill
71               Pentland  16.00  6200   2.377778   2.785000      hill
72                  Tinto   4.50  1500   0.499444   0.581111      hill
74                 Elrick   3.60   650   0.358056   0.442500     relay
75                Gondola   2.50  2000   0.387222   0.518889    uphill
76            Greenmantle   2.00   650   0.254444   0.316667     other

### Задание 10

Создать столбец `time_min`, который содержит время маршрута, измеренное в минутах.

In [88]:
dat['time_min']=dat['time']*60
dat

                    id  dist climb      time     timef    type    time_min
0   Aonach Mor Gondola   2.0  2000  0.403611  0.518889  uphill   24.216667
1    Broughton Brewery   2.0   650  0.254444  0.316667   other   15.266667
2          El-Brim-Ick   3.0   750  0.485833  0.389167   other   29.150000
3   The Devils Burdens  21.0  4100  2.399722  3.093333   relay  143.983333
4        Tiso Carnethy   6.0  2500  0.782222  0.919167    hill   46.933333
..                 ...   ...   ...       ...       ...     ...         ...
72               Tinto   4.5  1500  0.499444  0.581111    hill   29.966667
73          Druim Fada   6.5  1000  0.751111  0.972222   other   45.066667
74              Elrick   3.6   650  0.358056  0.442500   relay   21.483333
75             Gondola   2.5  2000  0.387222  0.518889  uphill   23.233333
76         Greenmantle   2.0   650  0.254444  0.316667   other   15.266667

[77 rows x 7 columns]

### Задание 11

Создать столбец `year` с годом соревнований (везде 2000 год). Внимание: столбец с годом должен быть числовым (целочисленным).

In [96]:
dat['year']='2000'
dat['year']=dat['year'].astype(int)
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        77 non-null     object
 1   dist      77 non-null     float64
 2   climb     77 non-null     object
 3   time      77 non-null     float64
 4   timef     75 non-null     float64
 5   type      77 non-null     object
 6   time_min  77 non-null     float64
 7   year      77 non-null     int32
dtypes: float64(4), int32(1), object(3)
memory usage: 4.6+ KB

.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Дополнительное (необязательное) задание.
<br>

### Задание 1

Загрузить датафрейм из файла `extraversion.csv`, используя код ниже. При этом файл `extraversion.csv` должен находиться в той же папке, что и ноутбук с решениями. Его можно поместить в ту же папку, нажав кнопку *Upload* в *Home*.

In [98]:

ps = pd.read_csv("extraversion.csv", encoding = "UTF-8")
ps

,Unnamed: 0.1,Unnamed: 0,sex,volunteer,Q 1,Q 2,Q 3,Q 4,Q 5,Q 6,...,Q 48,Q 49,Q 50,Q 51,Q 52,Q 53,Q 54,Q 55,Q 56,Q 57
0,0,1,Женский,Нет,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Нет,Нет,Да
1,1,2,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет
2,2,3,Женский,Да,Да,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
3,3,4,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Нет,Нет,Нет,Да,Нет,Нет
4,4,5,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
5,5,6,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,...,Нет,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Нет
6,6,7,Женский,Нет,Да,Нет,Нет,Да,Да,Нет,...,Да,Да,Нет,Нет,Да,Да,Да,Да,Нет,Нет
7,7,8,Женский,Да,Да,Да,Да,Нет,Да,Да,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
8,8,9,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Нет
9,9,10,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Да,Нет,Нет,Нет,Да,Да,Да,Да,Нет
10,10,11,Мужской,Нет,Нет,Да,Нет,Нет,Да,Да,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
11,11,12,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Да,Да,Нет
12,12,13,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
13,13,14,Женский,Нет,Да,Да,Нет,Да,Да,Нет,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
14,14,15,Женский,Нет,Нет,Нет,Нет,Да,Да,Нет,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Нет
15,15,16,Женский,Нет,Да,Да,Да,Нет,Да,Нет,...,Да,Нет,Да,Нет,Да,Да,Да,Да,Да,Да
16,16,17,Женский,Нет,Да,Да,Нет,Нет,Нет,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
17,17,18,Женский,Нет,Да,Нет,Да,Да,Нет,Нет,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Да,Да,Нет
18,18,19,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Нет,Да
19,19,20,Женский,Нет,Нет,Нет,Да,Да,Да,Нет,...,Да,Нет,Да,Да,Да,Нет,Да,Нет,Да,Да
20,20,21,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
21,21,22,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Нет,Нет,Нет,Нет,Да,Нет,Нет,Да,Нет,Нет
22,22,23,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Да,Нет,Да,Нет
23,23,24,Мужской,Да,Да,Да,Нет,Нет,Да,Да,...,Нет,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет
24,24,25,Мужской,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Нет,Да,Да,Нет,Да
25,25,26,Женский,Да,Нет,Да,Нет,Нет,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
26,26,27,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Нет,Да,Да,Да,Да,Да,Нет,Да,Нет,Нет
27,27,28,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Да,Нет,Да,Да,Да,Да,Нет
28,28,29,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Нет,Да,Да,Да,Да,Нет,Нет,Да,Да,Да
29,29,30,Женский,Нет,Нет,Нет,Нет,Нет,Да,Да,...,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да,Нет
30,30,31,Женский,Да,Да,Да,Нет,Да,Нет,Нет,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
31,31,32,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
32,32,33,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Нет,Да,Нет,Нет
33,33,34,Мужской,Нет,Нет,Да,Нет,Да,Да,Нет,...,Да,Нет,Да,Нет,Да,Нет,Нет,Нет,Да,Нет
34,34,35,Женский,Нет,Да,Да,Да,Нет,Да,Да,...,Нет,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
35,35,36,Женский,Да,Да,Да,Нет,Да,Да,Нет,...,Да,Нет,Нет,Да,Да,Нет,Да,Да,Нет,Нет
36,36,37,Женский,Нет,Да,Да,Да,Нет,Да,Нет,...,Да,Да,Да,Нет,Да,Да,Да,Да,Да,Нет
37,37,38,Женский,Нет,Да,Нет,Нет,Нет,Да,Да,...,Да,Да,Нет,Нет,Нет,Нет,Нет,Да,Нет,Нет
38,38,39,Женский,Нет,Да,Нет,Нет,Нет,Да,Нет,...,Да,Нет,Да,Нет,Нет,Нет,Нет,Да,Да,Да
39,39,40,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Да,Да,Да,Да
40,40,41,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,...,Да,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Да
41,41,42,Женский,Да,Да,Да,Нет,Нет,Да,Нет,...,Да,Нет,Нет,Нет,Да,Да,Да,Да,Да,Нет
42,42,43,Женский,Да,Да,Нет,Нет,Нет,Да,Да,...,Да,Нет,Да,Да,Да,Да,Нет,Да,Да,Нет
43,43,44,Женский,Нет,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Нет,Нет,Да,Нет,Нет,Нет,Да,Нет
44,44,45,Женский,Да,Да,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Да,Нет,Да,Да,Да
45,45,46,Женский,Нет,Да,Да,Нет,Нет,Да,Да,...,Да,Нет,Да,Нет,Да,Нет,Нет,Да,Да,Да
46,46,47,Женский,Да,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Да,Нет,Да,Да,Нет,Да,Да,Нет
47,47,48,Женский,Нет,Нет,Нет,Нет,Да,Да,Да,...,Да,Нет,Нет,Да,Да,Нет,Да,Нет,Нет,Нет
48,48,49,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Да,Да,Нет,Нет,Да,Да,Нет,Нет,Нет
49,49,50,Женский,Да,Нет,Нет,Нет,Нет,Да,Нет,...,Да,Нет,Да,Нет,Да,Нет,Да,Да,Да,Нет
50,50,51,Женский,Нет,Да,Да,Нет,Нет,Да,Нет,...,Да,Нет,Нет,Нет,Да,Да,Нет,Да,Да,Да
51,51,52,Женский,Да,Да,Да,Нет,Да,Да,Да,...,Да,Нет,Да,Да,Да,Да,Да,Да,Нет,Нет

Файл содержит результаты учебного психометрического исследования, целью которого является выявление связи между уровнем экстраверсии человека и его склонности к участию в волонтёрской деятельности. Датафрейм содержит следующие столбцы:

* `sex`: пол респондента (Женский, Мужской);
* `volunteer`: регулярное участие в волонтёрской деятельности (Да, Нет);
* `Q 1` - `Q 57`: ответы на вопросы по анкете Айзенка (Да, Нет), информацию об анкете и сами вопросы можно найти на [этой](http://ipp.hse.ru/57-testytest-ajzenka-ekstraversiya-introversiya-nejrotizm) странице.

In [ ]:
### YOUR CODE HERE ###

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [100]:
ps.shape #(52, 61)

(52, 61)

### Задание 3

Переименовать столбцы `Q 1`-`Q 57` в `Q1`-`Q57`, другими словами, убрать в названиях всех столбцов пробелы в середине (если есть). 

**Подсказка 1:** Метод `.replace()` для строк на [pythontutor.ru](https://pythontutor.ru/lessons/str/).

**Подсказка 2:** Для выполнения этого задания можно написать функцию, которая будет заменять пробелы на «пустоту», а потом применить её с помощью функции `map()` ко всем элементам списка. Пример ниже иллюстрирует применение функции для изменения регистра текста.

In [110]:

list(ps.columns)

['Unnamed: 0.1',
 'Unnamed: 0',
 'sex',
 'volunteer',
 'Q 1',
 'Q 2',
 'Q 3',
 'Q 4',
 'Q 5',
 'Q 6',
 'Q 7',
 'Q 8',
 'Q 9',
 'Q 10',
 'Q 11',
 'Q 12',
 'Q 13',
 'Q 14',
 'Q 15',
 'Q 16',
 'Q 17',
 'Q 18',
 'Q 19',
 'Q 20',
 'Q 21',
 'Q 22',
 'Q 23',
 'Q 24',
 'Q 25',
 'Q 26',
 'Q 27',
 'Q 28',
 'Q 29',
 'Q 30',
 'Q 31',
 'Q 32',
 'Q 33',
 'Q 34',
 'Q 35',
 'Q 36',
 'Q 37',
 'Q 38',
 'Q 39',
 'Q 40',
 'Q 41',
 'Q 42',
 'Q 43',
 'Q 44',
 'Q 45',
 'Q 46',
 'Q 47',
 'Q 48',
 'Q 49',
 'Q 50',
 'Q 51',
 'Q 52',
 'Q 53',
 'Q 54',
 'Q 55',
 'Q 56',
 'Q 57']

In [109]:
ps.columns=ps.replace[(' ', '')]

TypeError: 'method' object is not subscriptable

### Задание 4

Выбрать столбцы `Q1`, `Q3`, `Q8`, `Q10`, `Q13`, `Q17`, `Q22`, `Q25`, `Q27`, `Q39`, `Q44`, `Q46`, `Q49`, `Q53`, `Q56` и сохранить их в отдельный датафрейм `extra_yes`. 

Выбрать столбцы `Q5`, `Q15`, `Q20`, `Q29`, `Q32`, `Q34`, `Q37`,`Q41`, `Q51` и сохранить их в отдельный датафрейм `extra_no`.

Эти столбцы будут использоваться для вычисления индекса экстраверсии.

In [ ]:
### YOUR CODE HERE ###

### Задание 5

Посчитать для каждой строки в датафрейме `extra_yes` число ответов `"Да"` и полученный результат сохранить в переменную `extra_yes_sum`. Посчитать для каждой строки в датафрейме `extra_no` число ответов `"Нет"` и полученный результат сохранить в переменную `extra_no_sum`.

**Подсказка 1:** метод `.isin()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html) `pandas`.

**Подсказка 2:** метод `.sum()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html) `pandas`.

In [ ]:
### YOUR CODE HERE ###

### Задание 6

Добавить в исходный датафрейм столбец `extra`, который представляет собой индекс экстраверсии, который считается так: сумма числа ответов "Да" в `extra_yes` и числа ответов "Нет" в `extra_no`.

In [ ]:
### YOUR CODE HERE ###

### Задание 7

Добавить в исходный датафрейм столбец `female`, состоящий из значений 0 и 1 (0 — Мужской, 1 — Женский). 

**Подсказка:** возможно, пригодится метод `.astype()` для [Series](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Series.astype.html) в `pandas`, он преобразует типы столбцов.

In [ ]:
### YOUR CODE HERE ###

### Задание 8

Выбрать из исходного датафрейма строки, которые соответствуют либо волонтёрам с индексом экстраверсии выше 15, либо не-волонтёрам с индексом экстраверсии ниже 15. Сохранить в датафрейм `pure`.

In [ ]:
### YOUR CODE HERE ###

### Задание 9

Определить (любым способом, кроме явного подсчёта), сколько волонтёров и не-волонтёров в датафрейме `pure`.

In [ ]:
### YOUR CODE HERE ###

### Задание 10

Определить минимальное, максимальное, среднее и медианное значение индекса экстраверсии в датафрейме `pure`. Сохранить полученные результаты в отдельные переменные (их должно быть 4).

Добавить в датафрейм `pure` столбец `high`, состоящий из 0 и 1, где 1 соответствует респондентам, уровень экстраверсии которых выше значения $m = \max\{\text{median}, \text{mean}\}$, то есть максимума из медианного и среднего значения, а 0 — респондентам с уровнем экстраверсии не выше $m$.

In [ ]:
### YOUR CODE HERE ###